In [1]:
from solver import complementary_solver
import numpy as np

V_mx = np.array([[10, 20, 30, 40, 50, 60], 
                 [10, 20, 30, 40, 50, 60],
                 [30, 50, 30, 40, 50, 60],
                 [10, 20, 30, 40, 80, 60],
                 [10, 20, 30, 40, 50, 60],
                 [10, 20, 30, 40, 50, 60]])

X_mx, Y_vect = complementary_solver(V_mx, verbose=True)

Solver Status: OPTIMAL
Objective value: 290.0

Decision Variables (x[i][j]):
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 1 1 0 0 0]
 [0 0 0 1 1 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 1]]

Binary Variables y:
[1 1 0 0 1 1]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 1 1 0 0 0]
 [0 0 0 1 1 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 1]] [1 1 0 0 1 1]


In [ ]:
from pulp import LpMaximize, LpProblem, LpVariable, lpSum

# Definizione del problema
model = LpProblem(name="binary_optimization", sense=LpMaximize)

# Insieme P (per semplicità assumiamo un P fisso)
P = range(5)  # esempio con 5 elementi

# Variabili binarie x e y
x = LpVariable.dicts("x", ((i, j) for i in P for j in P), cat='Binary')
y = LpVariable.dicts("y", (i for i in P), cat='Binary')

# Coefficienti v (ipotizziamo valori casuali o prefissati)
v = {(i, j): (i + j) for i in P for j in P}  # esempio di valori

# Funzione obiettivo
model += lpSum(x[i, j] * v[i, j] for i in P for j in P)

# Vincoli
M = len(P)  # P come valore grande

for i in P:
    for j in P:
        model += x[i, j] >= 0
        model += x[i, j] <= 1

for i in P:
    model += y[i] >= 0
    model += y[i] <= 1

for i in P:
    model += lpSum(x[i, j] for j in P if j != i) >= 1 - M * y[i]
    model += lpSum(x[j, i] for j in P) <= M * y[i]
    model += lpSum(x[j, i] for j in P) >= 1 - M * (1 - y[i])
    model += lpSum(x[j, i] for j in P) <= 1 + M * (1 - y[i])
    model += lpSum(x[i, j] for j in P if j != i) <= M * (1 - y[i])

# Risoluzione del problema
model.solve()

# Output dei risultati
for i in P:
    for j in P:
        print(f"x[{i},{j}] = {x[i,j].varValue}")
for i in P:
    print(f"y[{i}] = {y[i].varValue}")

In [ ]:
from pulp import LpMaximize, LpProblem, LpVariable, lpSum

# Definizione del problema
model = LpProblem(name="binary_optimization", sense=LpMaximize)

# Insieme P (per semplicità assumiamo un P fisso)
P = ["A", "B", "C", "D", "E", "F"]  # insieme di prodotti

# Variabili binarie x e y
x = LpVariable.dicts("x", ((i, j) for i in P for j in P), cat='Binary')
y = LpVariable.dicts("y", (i for i in P), cat='Binary')

# Matrice V dai valori forniti
v = {
    ("A", "A"): 10, ("A", "B"): 30, ("A", "C"): 40, ("A", "D"): 50, ("A", "E"): 60, ("A", "F"): 70,
    ("B", "A"): 30, ("B", "B"): 20, ("B", "C"): 50, ("B", "D"): 60, ("B", "E"): 70, ("B", "F"): 80,
    ("C", "A"): 60, ("C", "B"): 80, ("C", "C"): 30, ("C", "D"): 70, ("C", "E"): 80, ("C", "F"): 90,
    ("D", "A"): 50, ("D", "B"): 60, ("D", "C"): 70, ("D", "D"): 40, ("D", "E"): 120, ("D", "F"): 100,
    ("E", "A"): 60, ("E", "B"): 70, ("E", "C"): 80, ("E", "D"): 90, ("E", "E"): 50, ("E", "F"): 110,
    ("F", "A"): 70, ("F", "B"): 80, ("F", "C"): 90, ("F", "D"): 100, ("F", "E"): 110, ("F", "F"): 60
}

# Funzione obiettivo
model += lpSum(x[i, j] * v[i, j] for i in P for j in P)

# Vincoli
M = len(P)  # P come valore grande

for i in P:
    for j in P:
        model += x[i, j] >= 0
        model += x[i, j] <= 1

for i in P:
    model += y[i] >= 0
    model += y[i] <= 1

for i in P:
    model += lpSum(x[i, j] for j in P if j != i) >= 1 - M * y[i]
    model += lpSum(x[j, i] for j in P) <= M * y[i]
    model += lpSum(x[j, i] for j in P) >= 1 - M * (1 - y[i])
    model += lpSum(x[j, i] for j in P) <= 1 + M * (1 - y[i])
    model += lpSum(x[i, j] for j in P if j != i) <= M * (1 - y[i])

# Risoluzione del problema
model.solve()

# Output dei risultati
for i in P:
    for j in P:
        print(f"x[{i},{j}] = {x[i,j].varValue}")
for i in P:
    print(f"y[{i}] = {y[i].varValue}")


In [ ]:
from pulp import LpMaximize, LpProblem, LpVariable, lpSum

# Definizione del problema
model = LpProblem(name="binary_optimization", sense=LpMaximize)

# Insieme P (per semplicità assumiamo un P fisso)
P = range(6)  # insieme di prodotti numerici

# Variabili binarie x e y
x = LpVariable.dicts("x", ((i, j) for i in P for j in P), cat='Binary')
y = LpVariable.dicts("y", (i for i in P), cat='Binary')

# Matrice V dai valori forniti
v = {
    (0, 0): 10, (0, 1): 30, (0, 2): 40, (0, 3): 50, (0, 4): 60, (0, 5): 70,
    (1, 0): 30, (1, 1): 20, (1, 2): 50, (1, 3): 60, (1, 4): 70, (1, 5): 80,
    (2, 0): 60, (2, 1): 80, (2, 2): 30, (2, 3): 70, (2, 4): 80, (2, 5): 90,
    (3, 0): 50, (3, 1): 60, (3, 2): 70, (3, 3): 40, (3, 4): 120, (3, 5): 100,
    (4, 0): 60, (4, 1): 70, (4, 2): 80, (4, 3): 90, (4, 4): 50, (4, 5): 110,
    (5, 0): 70, (5, 1): 80, (5, 2): 90, (5, 3): 100, (5, 4): 110, (5, 5): 60
}

# Funzione obiettivo
model += lpSum(x[i, j] * v[i, j] for i in P for j in P)

# Vincoli
M = len(P)  # P come valore grande

for i in P:
    for j in P:
        model += x[i, j] >= 0
        model += x[i, j] <= 1

for i in P:
    model += y[i] >= 0
    model += y[i] <= 1

for i in P:
    model += lpSum(x[i, j] for j in P if j != i) >= 1 - M * y[i]
    model += lpSum(x[j, i] for j in P) <= M * y[i]
    model += lpSum(x[j, i] for j in P) >= 1 - M * (1 - y[i])
    model += lpSum(x[j, i] for j in P) <= 1 + M * (1 - y[i])
    model += lpSum(x[i, j] for j in P if j != i) <= M * (1 - y[i])

# Risoluzione del problema
model.solve()

# Output della matrice x in forma compatta
print("Matrice x:")
for i in P:
    print(" ".join(str(int(x[i, j].varValue)) for j in P))

# Output delle variabili y
print("Variabili y:")
print(" ".join(str(int(y[i].varValue)) for i in P))


In [ ]:
import pulp
import numpy as np

# Define the problem
prob = pulp.LpProblem("Integer_Programming_Problem", pulp.LpMaximize)

# Define the set P (assuming P is of size n)
n = 10  # Example size, modify as needed
P = range(n)

# Define variables
x = {(i, j): pulp.LpVariable(f"x_{i}_{j}", 0, 1, pulp.LpBinary) for i in P for j in P}
y = {i: pulp.LpVariable(f"y_{i}", 0, 1, pulp.LpBinary) for i in P}

# Define the coefficients v_ij (random values for this example)
v = np.random.rand(n, n)  # Modify as needed
n = 1  # Example value for P, modify as needed

# Objective function
prob += pulp.lpSum(x[i, j] * v[i, j] for i in P for j in P)

# Constraints
for i in P:
    prob += sum(x[i, j] for j in P if j != i) >= 1 - n * y[i]
    prob += sum(x[i, j] for j in P if j != i) <= n * y[i]
    prob += x[i, i] <= 1 + n * y[i]
    prob += x[i, i] >= 1 - n * y[i]
    prob += sum(x[j, i] for j in P) >= 1 - n * (1 - y[i])
    prob += sum(x[j, i] for j in P) <= 1 + n * (1 - y[i])
    prob += sum(x[j, i] for j in P if j != i) <= n * (1 - y[i])

# Solve the problem
prob.solve()

# Print the results
print("Objective value:", pulp.value(prob.objective))
for i in P:
    for j in P:
        print(f"x[{i},{j}] =", pulp.value(x[i, j]))
    print(f"y[{i}] =", pulp.value(y[i]))

In [ ]:
import pulp
import numpy as np

# Define the problem
prob = pulp.LpProblem("Integer_Programming_Problem", pulp.LpMaximize)

# Define the set P (assuming P is of size 6 based on the matrix)
n = 6  # Size of the matrix
P = range(n)

# Define variables
x = {(i, j): pulp.LpVariable(f"x_{i}_{j}", 0, 1, pulp.LpBinary) for i in P for j in P}
y = {i: pulp.LpVariable(f"y_{i}", 0, 1, pulp.LpBinary) for i in P}

# Define the matrix v_ij from the provided image
v = np.array([
    [10, 20, 30, 40, 50, 60],
    [10, 20, 30, 40, 50, 60],
    [30, 50, 30, 40, 50, 60],
    [10, 20, 30, 40, 80, 60],
    [10, 20, 30, 40, 50, 60],
    [10, 20, 30, 40, 50, 60]
])

# Print the matrix
print("Matrix v_ij:")
print(v)
print("\n")

# Objective function
prob += pulp.lpSum(x[i, j] * v[i, j] for i in P for j in P)

# Constraints
for i in P:
    prob += sum(x[i, j] for j in P if j != i) >= 1 - n * y[i], f"C1_{i}"
    prob += sum(x[i, j] for j in P if j != i) <= n * y[i], f"C2_{i}"
    prob += x[i, i] <= 1 + n * y[i], f"C3_{i}"
    prob += x[i, i] >= 1 - n * y[i], f"C4_{i}"
    prob += sum(x[j, i] for j in P) >= 1 - n * (1 - y[i]), f"C5_{i}"
    prob += sum(x[j, i] for j in P) <= 1 + n * (1 - y[i]), f"C6_{i}"
    prob += sum(x[j, i] for j in P if j != i) <= n * (1 - y[i]), f"C7_{i}"

# Solve the problem
prob.solve()

# Output results
print("Solver Status:", pulp.LpStatus[prob.status])
print("Objective value:", pulp.value(prob.objective))

# Print the matrix v_ij
print("Matrix v_ij:")
print(v)

# Print x and y variables
print("\nDecision Variables (x[i][j]):")
for i in P:
    for j in P:
        print(f"x[{i},{j}] = {int(pulp.value(x[i, j])) if pulp.value(x[i, j]) is not None else 'None'}", end="\t")
    print()

print("\nBinary Variables y:")
for i in P:
    print(f"y[{i}] = {int(pulp.value(y[i])) if pulp.value(y[i]) is not None else 'None'}")


In [ ]:
from ortools.linear_solver import pywraplp
import numpy as np

# Create the solver
solver = pywraplp.Solver.CreateSolver('SCIP')
if not solver:
    raise Exception("Solver not available")

# Define the set P (assuming P is size 6 based on the matrix)
n = 6  # Size of the matrix
P = range(n)

# Define variables
x = {}
y = {}
for i in P:
    for j in P:
        x[i, j] = solver.BoolVar(f"x_{i}_{j}")
    y[i] = solver.BoolVar(f"y_{i}")

# Define the matrix v_ij from the provided image
v = np.array([
    [10, 20, 30, 40, 50, 60],
    [10, 20, 30, 40, 50, 60],
    [30, 50, 30, 40, 50, 60],
    [10, 20, 30, 40, 80, 60],
    [10, 20, 30, 40, 50, 60],
    [10, 20, 30, 40, 50, 60]
])

# Print the matrix
print("Matrix v_ij:")
print(v)
print("\n")

# Objective function
solver.Maximize(solver.Sum(x[i, j] * v[i, j] for i in P for j in P))

# Constraints
for i in P:
    solver.Add(solver.Sum(x[i, j] for j in P if j != i) >= 1 - n * y[i])
    solver.Add(solver.Sum(x[j, i] for j in P if j != i) <= n * y[i])
    solver.Add(x[i, i] <= 1 + n * y[i])
    solver.Add(x[i, i] >= 1 - n * y[i])
    solver.Add(solver.Sum(x[j, i] for j in P) >= 1 - n * (1 - y[i]))
    solver.Add(solver.Sum(x[j, i] for j in P) <= 1 + n * (1 - y[i]))
    solver.Add(solver.Sum(x[i, j] for j in P if j != i) <= n * (1 - y[i]))

# Solve the problem
status = solver.Solve()

# Output results
if status == pywraplp.Solver.OPTIMAL:
    print("Solver Status: OPTIMAL")
    print("Objective value:", solver.Objective().Value())
else:
    print("Solver did not find an optimal solution.")

# Print decision variables as integer matrix
print("\nDecision Variables (x[i][j]):")
x_values = np.zeros((n, n), dtype=int)
y_values = np.zeros(n, dtype=int)

for i in P:
    for j in P:
        x_values[i, j] = int(x[i, j].solution_value())
print(x_values)

print("\nBinary Variables y:")
y_values = np.array([int(y[i].solution_value()) for i in P])
print(y_values)